In [148]:
import pandas as pd
print(pd.__version__)

3.0.0

pandas serise niye alochona

In [149]:
import numpy as np
import pandas as pd

In [150]:
data=np.arange(5,10)
data

array([5, 6, 7, 8, 9])

amar kase simple np array ase .pandas seris holo akta numpy array er pandas represantation .

In [151]:
pd_series=pd.Series(data=data)
pd_series

0    5
1    6
2    7
3    8
4    9
dtype: int64

numpy array ke pandas seris ea convert korle

বাম পাশে index
ডান পাশে value

বাম পাশের data

এটা হলো Series function এর parameter name।

মানে pd.Series() এর ভিতরে একটা argument আছে যার নাম data।ডান পাশের data

এটা হলো তোমার বানানো variable।

S borohater hote hbe .S dara ei boja jai ata akta class.

সংক্ষেপে পার্থক্য
NumPy Array	Pandas Seriesশুধু data থাকে	 besi...fast	data analysis এর জন্য panads ভালো   pandas ea data +index valo

In [152]:
pd.Series(data=data, index=['a','b','c','d','e'])

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [153]:
pd_series[0]

np.int64(5)

numpy integer 64 bit er 5

In [154]:
index=['a','b','c','d','e']
pd_series2=pd.Series(data=data, index=index)
pd_series2

a    5
b    6
c    7
d    8
e    9
dtype: int64

custom index setup.....

In [155]:
pd_series2['a']

np.int64(5)

In [156]:
pd_series2["b"]

np.int64(6)

akn jodi first pandas series er jonno custom index setup korte pari?pd_series=pd.Series(data=data) akne? obbosoy pari akhetre akta jamela ase seta holo jokon pd serirs tare make korsi tokon customindex ke setup kori nai,,,,,,ei index golo already set hoia gese agoloke akn overwrite korte hbe .

In [157]:
pd_series.index #ata akta method, akta property

RangeIndex(start=0, stop=5, step=1)

start 0 theke stop 5 step 1 kore ....atake overwrite korte pari aivave

In [158]:
pd_series.index=index
pd_series

a    5
b    6
c    7
d    8
e    9
dtype: int64

akn dekha jasse ager index dlt hoye index er golo asche just wow pandas.

akta pandas series akta numpy  array

In [159]:
#data=data  bam paser data tai dictonary use korte pari 
data={
    "a":2,
    "b":456,
    "c":78
}
pd_series3=pd.Series(data=data)
pd_series3

a      2
b    456
c     78
dtype: int64

pandas Series  .Dimension
1D .Structure : Single column  .

pandas dataframe 2d dimentation structure holo multiple column

Pandas DataFrame Porichiti

In [160]:
data=np.random.rand(6,5)

In [161]:
data

array([[0.52463307, 0.02333317, 0.91112606, 0.3561578 , 0.41974754],
       [0.77072665, 0.33199653, 0.1382726 , 0.13243162, 0.92155604],
       [0.08245459, 0.30085502, 0.01359586, 0.00867498, 0.88274406],
       [0.68178527, 0.70461683, 0.9800294 , 0.12340548, 0.32444923],
       [0.83335262, 0.43832773, 0.69786071, 0.85465135, 0.03245749],
       [0.07849665, 0.04037259, 0.10875851, 0.68852122, 0.02908014]])

In [162]:
df=pd.DataFrame(data=data)
df

          0         1         2         3         4
0  0.524633  0.023333  0.911126  0.356158  0.419748
1  0.770727  0.331997  0.138273  0.132432  0.921556
2  0.082455  0.300855  0.013596  0.008675  0.882744
3  0.681785  0.704617  0.980029  0.123405  0.324449
4  0.833353  0.438328  0.697861  0.854651  0.032457
5  0.078497  0.040373  0.108759  0.688521  0.029080

ata korle tabuler represation pabo 2d dimentational numpy array tar.................accha numpy te 2d array tar row er index onojaiyi nite pari column nite pari mane onk kicho korte pari numpy ea ata slising kore newa hoi but pandas ea ata onk easy hoia jai .

In [163]:
df[0]# 0 column er value ata

0    0.524633
1    0.770727
2    0.082455
3    0.681785
4    0.833353
5    0.078497
Name: 0, dtype: float64

In [164]:
type(df[0])

pandas.Series

so akta dataframe holo series

In [165]:
type(df) #full dataframe er type

pandas.DataFrame

In [166]:
df2=pd.DataFrame(
    data=data,
    index=["turzo","shuvo","tanjim","shahin","sakib","rafiq"],
    columns=["a","b","c","d","e"]

                 


)

In [167]:
df2

               a         b         c         d         e
turzo   0.524633  0.023333  0.911126  0.356158  0.419748
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556
tanjim  0.082455  0.300855  0.013596  0.008675  0.882744
shahin  0.681785  0.704617  0.980029  0.123405  0.324449
sakib   0.833353  0.438328  0.697861  0.854651  0.032457
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080

just               wow

In [168]:
df2["a"]

turzo     0.524633
shuvo     0.770727
tanjim    0.082455
shahin    0.681785
sakib     0.833353
rafiq     0.078497
Name: a, dtype: float64

In [169]:
df2.loc['turzo']

a    0.524633
b    0.023333
c    0.911126
d    0.356158
e    0.419748
Name: turzo, dtype: float64

In [170]:
df2.loc['turzo','a']#df.loc[row_label, column_label]

np.float64(0.5246330742297555)

just wow

In [171]:
df2[["a","b"]]
#error because of multi index, akta column er name a ar b nai, 
# akta column er name a,b nai

               a         b
turzo   0.524633  0.023333
shuvo   0.770727  0.331997
tanjim  0.082455  0.300855
shahin  0.681785  0.704617
sakib   0.833353  0.438328
rafiq   0.078497  0.040373

ei data frame ea new column kibabe add korbo

In [172]:
df2["shuvro"]=np.random.rand(6)
df2

               a         b         c         d         e    shuvro
turzo   0.524633  0.023333  0.911126  0.356158  0.419748  0.795832
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556  0.091586
tanjim  0.082455  0.300855  0.013596  0.008675  0.882744  0.842597
shahin  0.681785  0.704617  0.980029  0.123405  0.324449  0.969199
sakib   0.833353  0.438328  0.697861  0.854651  0.032457  0.000165
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080  0.713460

dataframe theke column remove kora.ata korar jonno data frame eri akta method use korte pari drop method.bydefault row set kora thake.

In [173]:
df2.drop("tanjim")

               a         b         c         d         e    shuvro
turzo   0.524633  0.023333  0.911126  0.356158  0.419748  0.795832
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556  0.091586
shahin  0.681785  0.704617  0.980029  0.123405  0.324449  0.969199
sakib   0.833353  0.438328  0.697861  0.854651  0.032457  0.000165
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080  0.713460

In [174]:
df2.drop(columns="a")

               b         c         d         e    shuvro
turzo   0.023333  0.911126  0.356158  0.419748  0.795832
shuvo   0.331997  0.138273  0.132432  0.921556  0.091586
tanjim  0.300855  0.013596  0.008675  0.882744  0.842597
shahin  0.704617  0.980029  0.123405  0.324449  0.969199
sakib   0.438328  0.697861  0.854651  0.032457  0.000165
rafiq   0.040373  0.108759  0.688521  0.029080  0.713460

In [175]:
df2

               a         b         c         d         e    shuvro
turzo   0.524633  0.023333  0.911126  0.356158  0.419748  0.795832
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556  0.091586
tanjim  0.082455  0.300855  0.013596  0.008675  0.882744  0.842597
shahin  0.681785  0.704617  0.980029  0.123405  0.324449  0.969199
sakib   0.833353  0.438328  0.697861  0.854651  0.032457  0.000165
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080  0.713460

df2 ager ta run korle main data theke remove hoi na ,,,,,,ata main data thekee hole jinista valo hobe na karon col ea onk data thakte pare future ea agolo drkar hote pare tai eijoonno drop method ta simply main data frame er cpy ke dibe jei cpy kealada variable er modde store korte pari and df theke col remov dekhte pabo,,,,,,,,,,,jeita ferot pabo ata new df

main data theke jodi col remove korte chai parmanently tahole inplace=True use 
korte hobe

In [176]:
df2.drop(columns="shuvro",inplace=True)
df2

               a         b         c         d         e
turzo   0.524633  0.023333  0.911126  0.356158  0.419748
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556
tanjim  0.082455  0.300855  0.013596  0.008675  0.882744
shahin  0.681785  0.704617  0.980029  0.123405  0.324449
sakib   0.833353  0.438328  0.697861  0.854651  0.032457
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080

new columngayeb hoia gese

In [177]:
df2

               a         b         c         d         e
turzo   0.524633  0.023333  0.911126  0.356158  0.419748
shuvo   0.770727  0.331997  0.138273  0.132432  0.921556
tanjim  0.082455  0.300855  0.013596  0.008675  0.882744
shahin  0.681785  0.704617  0.980029  0.123405  0.324449
sakib   0.833353  0.438328  0.697861  0.854651  0.032457
rafiq   0.078497  0.040373  0.108759  0.688521  0.029080

akn jodi kono column ke rmv korte chai tahole columns argument ke pass korte hbe .axis use korte pari axis ki?

In [178]:
df2.shape

(6, 5)

6,6 ata 2d array 6 row 6 column,,,,akhetre axis bolvo shape er index golo ke 6 ata 0 index  6 ata 1 index. 0 axis ea thakbe 6 ta value 1 axis ea thakbe 6 ta value

axis=0
rows বরাবর
প্রতিটি column নিয়ে কাজ করে..................axis=1
columns বরাবর
প্রতিটি row নিয়ে কাজ করে

In [179]:
import pandas as pd

df = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6],
    "C":[7,8,9]
})

print(df)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [180]:
df.drop("B", axis=1)

   A  C
0  1  7
1  2  8
2  3  9

akane col b dlt

In [181]:
df.drop(1, axis=0)

   A  B  C
0  1  4  7
2  3  6  9

এখানে index 1 row delete হবে।

সহজভাবে মনে রাখার ট্রিক

axis=0 → rows

axis=1 → columns

amra jokon data set niye kaz korbo tkn ques er ans khojbo je ata ase ni ota ase ni amn type tokon pandas "conditional selection niye " kaz korte hove

In [182]:
data=np.random.rand(8,5)
df=pd.DataFrame(
    data=data,
    index=['a','b','c','d','e','f','g','h'],
    columns=['A','B','C','D','E']
    )

df

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

In [183]:
df>0

      A     B     C     D     E
a  True  True  True  True  True
b  True  True  True  True  True
c  True  True  True  True  True
d  True  True  True  True  True
e  True  True  True  True  True
f  True  True  True  True  True
g  True  True  True  True  True
h  True  True  True  True  True

In [184]:
booldf=df>0

In [185]:
df[booldf]

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

sob golo 0 theke boro

In [186]:
df[df>0]

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

jodi chai col 4 er jonno0 theke boro ber korte

In [187]:
boolseris=df["D"]>0

In [188]:
df[boolseris]

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

In [189]:
df[df["D"]>0]#1 line ea

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

mutiple condition

In [190]:
(df["C"]>0) | (df["E"]<0)

a    True
b    True
c    True
d    True
e    True
f    True
g    True
h    True
dtype: bool

mane jekono akta true hoilei true

In [191]:
boolsrs=(df["C"]>0) | (df["E"]<0)

In [192]:
df[boolsrs]

          A         B         C         D         E
a  0.767727  0.110355  0.736634  0.973340  0.296851
b  0.143147  0.324222  0.953775  0.487582  0.426615
c  0.596038  0.247102  0.541389  0.009294  0.019628
d  0.924979  0.765147  0.331999  0.602416  0.636090
e  0.260833  0.309919  0.700526  0.851246  0.873803
f  0.515483  0.318674  0.656089  0.514293  0.978036
g  0.700198  0.508719  0.338230  0.976255  0.056725
h  0.145126  0.017110  0.481476  0.265963  0.500424

conditional selected data keonno khotaw use korte chaile atarew variable ea store korte pari

In [193]:
result=df[boolsrs]

In [194]:
result[["A","B"]]

          A         B
a  0.767727  0.110355
b  0.143147  0.324222
c  0.596038  0.247102
d  0.924979  0.765147
e  0.260833  0.309919
f  0.515483  0.318674
g  0.700198  0.508719
h  0.145126  0.017110

eiporo jinis ke 1 line ei kora jai

In [195]:
df[(df["C"]>0) | (df["E"]<0)][["A","B"]]

          A         B
a  0.767727  0.110355
b  0.143147  0.324222
c  0.596038  0.247102
d  0.924979  0.765147
e  0.260833  0.309919
f  0.515483  0.318674
g  0.700198  0.508719
h  0.145126  0.017110

AKTAR JAIGAI 2 TA INDEXING

In [196]:
groups = ["group1"]*3  + ["group2"]*3  
groups

['group1', 'group1', 'group1', 'group2', 'group2', 'group2']

In [197]:
groups = ["group1"]*3  + ["group2"]*3  
inside_groups=["row1","row2","row3"]*2
inside_groups

['row1', 'row2', 'row3', 'row1', 'row2', 'row3']

In [198]:
columns=["col1","col2"]
columns

['col1', 'col2']

In [199]:
groups = ["group1"]*3  + ["group2"]*3  
inside_groups=["row1","row2","row3"]*2
zip(groups, inside_groups)

zip 0bj er memory address dwa hoise,,,,,,zip korsi ata itarable hobe atake list ea conert korte pari    zip grop ar insidegrp ke ek korara jonno

In [200]:
list(zip(groups, inside_groups))

[('group1', 'row1'),
 ('group1', 'row2'),
 ('group1', 'row3'),
 ('group2', 'row1'),
 ('group2', 'row2'),
 ('group2', 'row3')]

zip() হলো Python এর একটি function, যা দুইটা বা একাধিক list এর element গুলোকে pair (জোড়া) বানায়।

In [201]:
a = [1,2,3]
b = ['a','b','c']
c= [True, False, True]

list(zip(a,b,c))

[(1, 'a', True), (2, 'b', False), (3, 'c', True)]

Multi indexing

In [202]:
ind_tuple=list(zip(groups, inside_groups))
ind_tuple

[('group1', 'row1'),
 ('group1', 'row2'),
 ('group1', 'row3'),
 ('group2', 'row1'),
 ('group2', 'row2'),
 ('group2', 'row3')]

In [203]:
index=pd.MultiIndex.from_tuples(tuples=ind_tuple)
#এটা ওই tuple গুলো দিয়ে 2-level index (hierarchical index) বানায়।

In [204]:
index

MultiIndex([('group1', 'row1'),
            ('group1', 'row2'),
            ('group1', 'row3'),
            ('group2', 'row1'),
            ('group2', 'row2'),
            ('group2', 'row3')],
           )

In [205]:
df=pd.DataFrame(
    data=np.random.rand(6,2),
    index=index,
    columns=columns
)

এখানে

np.random.rand(6,2) → 6 row, 2 column random data

index=index → আমরা যে MultiIndex বানিয়েছি সেটা ব্যবহার হয়েছে

columns=columns → column name (col1, col2)

এখানে index দুইটা level এ আছে:

Level 1 → group
Level 2 → row

In [206]:
df

                 col1      col2
group1 row1  0.099237  0.537861
       row2  0.953961  0.972860
       row3  0.111506  0.203358
group2 row1  0.511843  0.623655
       row2  0.550901  0.946021
       row3  0.259664  0.861086

indexing keno kora hoi :


1️⃣ Data কে group অনুযায়ী organize করার জন্য
2️⃣ সহজে group অনুযায়ী data বের করা যায়

In [207]:
df.loc['group1']

          col1      col2
row1  0.099237  0.537861
row2  0.953961  0.972860
row3  0.111506  0.203358

3️⃣ Complex dataset handle করতে

অনেক সময় data এমন হয়:

Country	City	Population
USA	New York	8M
USA	Chicago	2M
UK	London	9M

এখানে Country + City দুইটা level index লাগে।

4️⃣ Data analysis সহজ করার জন্য

MultiIndex থাকলে সহজে করা যায়:

grouping

aggregation

hierarchical data handling

In [208]:
group1=df.loc['group1']
group1

          col1      col2
row1  0.099237  0.537861
row2  0.953961  0.972860
row3  0.111506  0.203358

In [209]:
df.loc["group1"].loc["row1"]

col1    0.099237
col2    0.537861
Name: row1, dtype: float64

akn ami chai 2 group  eri  row 1 tare othoba group  1 er row 2 and 3 ke  tkn ki korbo?atar slv holo 

amaderindex er jonno akta name ke dite pari jeheto multiple indexesase seheto segoloke level onojaiyai alada alada vave use korar jonno amra agolor name dite pari group1 ke name dite pari groups and row goloke nam dite oari rows .

MultiIndex ব্যবহার করলে level এর নাম দেওয়া গুরুত্বপূর্ণ, তাহলে সহজে group বা row অনুযায়ী data access করা যায়।

In [210]:
df.index

MultiIndex([('group1', 'row1'),
            ('group1', 'row2'),
            ('group1', 'row3'),
            ('group2', 'row1'),
            ('group2', 'row2'),
            ('group2', 'row3')],
           )

In [211]:
df.index.names

FrozenList([None, None])

1️⃣ FrozenList কী?

FrozenList হলো pandas এর একটি immutable list (পরিবর্তন করা যায় না এমন list)।
এটা সাধারণত index বা column names রাখার জন্য ব্যবহার হয়।

2️⃣ [None, None] মানে কী?

তোমার index এ ২টা level আছে, কিন্তু তাদের কোনো নাম দেওয়া হয়নি।

মানে structure এমন:

Level 1 → group1, group2
Level 2 → row1, row2, row3

কিন্তু pandas এ তাদের নাম নেই, তাই দেখাচ্ছে:

[None, None]
3️⃣ নাম দিলে কী হবে
df.index.names = ['group','row']

এখন আবার check করলে:

df.index.names

Output হবে:

FrozenList(['group','row'])
সহজভাবে
FrozenList([None,None])

মানে:

২টা index level আছে

কিন্তু তাদের নাম দেওয়া হয়নি।

In [212]:
df.index.names=["groups","rows"]
df

                 col1      col2
groups rows
group1 row1  0.099237  0.537861
       row2  0.953961  0.972860
       row3  0.111506  0.203358
group2 row1  0.511843  0.623655
       row2  0.550901  0.946021
       row3  0.259664  0.861086

agolo ke use kore akta special method use korte pari seatar nam crss section method         ata row index er jonno bebohar hoi.

In [213]:
df.xs("group1")

          col1      col2
rows
row1  0.099237  0.537861
row2  0.953961  0.972860
row3  0.111506  0.203358

In [214]:
df.xs("group1")#cross section, group1 er cross section, group1 er data gula dibe

          col1      col2
rows
row1  0.099237  0.537861
row2  0.953961  0.972860
row3  0.111506  0.203358

2️⃣ row1 এর data (সব group থেকে)

In [215]:
df.xs('row1', level='rows')

            col1      col2
groups
group1  0.099237  0.537861
group2  0.511843  0.623655

এখানে rows দিয়ে বোঝানো হয়েছে MultiIndex এর দ্বিতীয় level এর নাম।

Pandas দিয়ে missing value handle করা।

mone koro akta dataset ea 3 ta column and hazar ta row ase ,,,hazar ta row er modde kiso valu empty kiso gayeb amn thakbe tai na ata kiabe handle kora jai,,,,,,most of time kiso row faka hoile asob gayeb korte pari somossa chara

In [216]:
data={
    "A":[1,2,np.nan,3],
    "B":[2,np.nan,np.nan,4],
    "C":[7,5,6,8]

}
df=pd.DataFrame(data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

In [217]:
df.dropna()#dropna mane je row gula te nan ache, oigula drop kore dibe

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  8

dropna method by default row dlt kore dei column dlt korle axis ta ante hbe

In [218]:
df.dropna(axis=1)#dropna axis=1 mane je column gula te nan ache, oigula drop kore dibe

   C
0  7
1  5
2  6
3  8

column rmv kora theke biroto thakte hbe .

In [219]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

df kinto parmanent chang hoi ni re vhai akn ki korar?korte hole akanew inplace nam ea argument pass korbo

In [220]:
df.dropna(axis=1,inplace=True)

In [221]:
df

   C
0  7
1  5
2  6
3  8

akane parmanently change hocche

In [222]:
data={
    "A":[1,2,np.nan,3],
    "B":[2,np.nan,np.nan,4],
    "C":[7,5,6,8]

}
df=pd.DataFrame(data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

In [223]:
df.dropna(thresh=2)

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
3  3.0  4.0  8

thresh কী?

thresh মানে minimum কতগুলো valid (non-NaN) value থাকতে হবে।

যদি তার কম থাকে তাহলে সেই row বা column delete হয়ে যাবে।

Onek golo misssing value thakle tokon kikorbo?

In [224]:
df.fillna(value="missing")

         A        B  C
0      1.0      2.0  7
1      2.0  missing  5
2  missing  missing  6
3      3.0      4.0  8

missing valu ke poron korbo oi colmn er mean valu er dara

In [225]:
df.fillna(value=df["C"].mean())

     A    B  C
0  1.0  2.0  7
1  2.0  6.5  5
2  6.5  6.5  6
3  3.0  4.0  8

In [226]:
df.fillna(value=df["A"].mean())

     A    B  C
0  1.0  2.0  7
1  2.0  2.0  5
2  2.0  2.0  6
3  3.0  4.0  8

jei column ea missing seta diye ei fillup korte hoibo

In [227]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

kinto main df kinto chane hoi na parmanently.

In [228]:
df.fillna({"B":df["B"].mean()},inplace=True)

     A    B  C
0  1.0  2.0  7
1  2.0  3.0  5
2  NaN  3.0  6
3  3.0  4.0  8

In [229]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  3.0  5
2  NaN  3.0  6
3  3.0  4.0  8

<!-- kinto data framekinto change hoi na mind it -->

<!-- kinto data frame parmanent kinto cahnge hoi na thik ache  -->